version: '3.8'

services:
  frontend:
    build:
      context: ../../frontend
      dockerfile: ../docker/frontend/Dockerfile
    ports:
      - "80:80"
    environment:
      - NODE_ENV=production
    depends_on:
      - backend
    networks:
      - ipams-network
    restart: always

  backend:
    build:
      context: ../../backend
      dockerfile: ../docker/backend/Dockerfile
    ports:
      - "5000:5000"
    environment:
      - FLASK_APP=run.py
      - FLASK_ENV=production
      - REDIS_URL=redis://redis:6379/0
    volumes:
      - ../../backend/uploads:/app/uploads
    depends_on:
      - redis
      - mysql
    networks:
      - ipams-network
    restart: always

  redis:
    image: redis:alpine
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data
    networks:
      - ipams-network
    restart: always

  mysql:
    image: mysql:8.0
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_DATABASE=ipams
      - MYSQL_USER=ipams_user
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
    volumes:
      - mysql-data:/var/lib/mysql
    networks:
      - ipams-network
    restart: always

networks:
  ipams-network:
    driver: bridge

volumes:
  redis-data:
  mysql-data: 